package entity;

import java.io.Serializable;
import java.util.Date;

public class SysUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password_hash
     *
     * @mbggenerated
     */
    private String passwordHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.security_stamp
     *
     * @mbggenerated
     */
    private String securityStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_type
     *
     * @mbggenerated
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobilephone
     *
     * @mbggenerated
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.display_name
     *
     * @mbggenerated
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.regist_time
     *
     * @mbggenerated
     */
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_logintime
     *
     * @mbggenerated
     */
    private Date lastLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_failedcount
     *
     * @mbggenerated
     */
    private Integer loginFailedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_failedtime
     *
     * @mbggenerated
     */
    private Date loginFailedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.work_state
     *
     * @mbggenerated
     */
    private Integer workState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_userid
     *
     * @mbggenerated
     */
    private String createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_userid
     *
     * @mbggenerated
     */
    private String updateUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_id
     *
     * @return the value of sys_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_id
     *
     * @param userId the value for sys_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password_hash
     *
     * @return the value of sys_user.password_hash
     *
     * @mbggenerated
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password_hash
     *
     * @param passwordHash the value for sys_user.password_hash
     *
     * @mbggenerated
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash == null ? null : passwordHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.security_stamp
     *
     * @return the value of sys_user.security_stamp
     *
     * @mbggenerated
     */
    public String getSecurityStamp() {
        return securityStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.security_stamp
     *
     * @param securityStamp the value for sys_user.security_stamp
     *
     * @mbggenerated
     */
    public void setSecurityStamp(String securityStamp) {
        this.securityStamp = securityStamp == null ? null : securityStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account_type
     *
     * @return the value of sys_user.account_type
     *
     * @mbggenerated
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account_type
     *
     * @param accountType the value for sys_user.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mobilephone
     *
     * @return the value of sys_user.mobilephone
     *
     * @mbggenerated
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mobilephone
     *
     * @param mobilephone the value for sys_user.mobilephone
     *
     * @mbggenerated
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id_card
     *
     * @return the value of sys_user.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id_card
     *
     * @param idCard the value for sys_user.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.display_name
     *
     * @return the value of sys_user.display_name
     *
     * @mbggenerated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.display_name
     *
     * @param displayName the value for sys_user.display_name
     *
     * @mbggenerated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.regist_time
     *
     * @return the value of sys_user.regist_time
     *
     * @mbggenerated
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.regist_time
     *
     * @param registTime the value for sys_user.regist_time
     *
     * @mbggenerated
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_logintime
     *
     * @return the value of sys_user.last_logintime
     *
     * @mbggenerated
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_logintime
     *
     * @param lastLogintime the value for sys_user.last_logintime
     *
     * @mbggenerated
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_failedcount
     *
     * @return the value of sys_user.login_failedcount
     *
     * @mbggenerated
     */
    public Integer getLoginFailedcount() {
        return loginFailedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_failedcount
     *
     * @param loginFailedcount the value for sys_user.login_failedcount
     *
     * @mbggenerated
     */
    public void setLoginFailedcount(Integer loginFailedcount) {
        this.loginFailedcount = loginFailedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_failedtime
     *
     * @return the value of sys_user.login_failedtime
     *
     * @mbggenerated
     */
    public Date getLoginFailedtime() {
        return loginFailedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_failedtime
     *
     * @param loginFailedtime the value for sys_user.login_failedtime
     *
     * @mbggenerated
     */
    public void setLoginFailedtime(Date loginFailedtime) {
        this.loginFailedtime = loginFailedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.work_state
     *
     * @return the value of sys_user.work_state
     *
     * @mbggenerated
     */
    public Integer getWorkState() {
        return workState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.work_state
     *
     * @param workState the value for sys_user.work_state
     *
     * @mbggenerated
     */
    public void setWorkState(Integer workState) {
        this.workState = workState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_userid
     *
     * @return the value of sys_user.create_userid
     *
     * @mbggenerated
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_userid
     *
     * @param createUserid the value for sys_user.create_userid
     *
     * @mbggenerated
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid == null ? null : createUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.createtime
     *
     * @return the value of sys_user.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.createtime
     *
     * @param createtime the value for sys_user.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_userid
     *
     * @return the value of sys_user.update_userid
     *
     * @mbggenerated
     */
    public String getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_userid
     *
     * @param updateUserid the value for sys_user.update_userid
     *
     * @mbggenerated
     */
    public void setUpdateUserid(String updateUserid) {
        this.updateUserid = updateUserid == null ? null : updateUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updatetime
     *
     * @return the value of sys_user.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updatetime
     *
     * @param updatetime the value for sys_user.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.openid
     *
     * @return the value of sys_user.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.openid
     *
     * @param openid the value for sys_user.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUser other = (SysUser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPasswordHash() == null ? other.getPasswordHash() == null : this.getPasswordHash().equals(other.getPasswordHash()))
            && (this.getSecurityStamp() == null ? other.getSecurityStamp() == null : this.getSecurityStamp().equals(other.getSecurityStamp()))
            && (this.getAccountType() == null ? other.getAccountType() == null : this.getAccountType().equals(other.getAccountType()))
            && (this.getMobilephone() == null ? other.getMobilephone() == null : this.getMobilephone().equals(other.getMobilephone()))
            && (this.getIdCard() == null ? other.getIdCard() == null : this.getIdCard().equals(other.getIdCard()))
            && (this.getDisplayName() == null ? other.getDisplayName() == null : this.getDisplayName().equals(other.getDisplayName()))
            && (this.getRegistTime() == null ? other.getRegistTime() == null : this.getRegistTime().equals(other.getRegistTime()))
            && (this.getLastLogintime() == null ? other.getLastLogintime() == null : this.getLastLogintime().equals(other.getLastLogintime()))
            && (this.getLoginFailedcount() == null ? other.getLoginFailedcount() == null : this.getLoginFailedcount().equals(other.getLoginFailedcount()))
            && (this.getLoginFailedtime() == null ? other.getLoginFailedtime() == null : this.getLoginFailedtime().equals(other.getLoginFailedtime()))
            && (this.getWorkState() == null ? other.getWorkState() == null : this.getWorkState().equals(other.getWorkState()))
            && (this.getCreateUserid() == null ? other.getCreateUserid() == null : this.getCreateUserid().equals(other.getCreateUserid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getOpenid() == null ? other.getOpenid() == null : this.getOpenid().equals(other.getOpenid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPasswordHash() == null) ? 0 : getPasswordHash().hashCode());
        result = prime * result + ((getSecurityStamp() == null) ? 0 : getSecurityStamp().hashCode());
        result = prime * result + ((getAccountType() == null) ? 0 : getAccountType().hashCode());
        result = prime * result + ((getMobilephone() == null) ? 0 : getMobilephone().hashCode());
        result = prime * result + ((getIdCard() == null) ? 0 : getIdCard().hashCode());
        result = prime * result + ((getDisplayName() == null) ? 0 : getDisplayName().hashCode());
        result = prime * result + ((getRegistTime() == null) ? 0 : getRegistTime().hashCode());
        result = prime * result + ((getLastLogintime() == null) ? 0 : getLastLogintime().hashCode());
        result = prime * result + ((getLoginFailedcount() == null) ? 0 : getLoginFailedcount().hashCode());
        result = prime * result + ((getLoginFailedtime() == null) ? 0 : getLoginFailedtime().hashCode());
        result = prime * result + ((getWorkState() == null) ? 0 : getWorkState().hashCode());
        result = prime * result + ((getCreateUserid() == null) ? 0 : getCreateUserid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getOpenid() == null) ? 0 : getOpenid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", passwordHash=").append(passwordHash);
        sb.append(", securityStamp=").append(securityStamp);
        sb.append(", accountType=").append(accountType);
        sb.append(", mobilephone=").append(mobilephone);
        sb.append(", idCard=").append(idCard);
        sb.append(", displayName=").append(displayName);
        sb.append(", registTime=").append(registTime);
        sb.append(", lastLogintime=").append(lastLogintime);
        sb.append(", loginFailedcount=").append(loginFailedcount);
        sb.append(", loginFailedtime=").append(loginFailedtime);
        sb.append(", workState=").append(workState);
        sb.append(", createUserid=").append(createUserid);
        sb.append(", createtime=").append(createtime);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", openid=").append(openid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}